# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UniversalLinkDev' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for UniversalLinkDev
  pod 'mob_linksdk'

end
